######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 10 03:22:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += modbus_client.cpp

INCLUDEPATH += libmodbus/src

LIBS += -L./libmodbus/src/.libs
LIBS += -lmodbus
