######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 10 03:22:43 2013
######################################################################

TEMPLATE = app
TARGET = mbServer
DESTDIR = ../
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += modbus_server.c

INCLUDEPATH += ../libmodbus/src \
    ../common

LIBS += -L../libmodbus/src/.libs
LIBS += -lmodbus
