######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 10 03:22:43 2013
######################################################################

TEMPLATE = app
TARGET = mbClient
DESTDIR = ../
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += modbus_client.c

INCLUDEPATH += ../libmodbus/src

LIBS += -L../libmodbus/src/.libs
LIBS += -lmodbus
